### ISSUE TITLE
import common_io, not found

### ISSUE THREAD

**Issue by DrobConsulting** [alibaba/graph-gpt#1]
ModuleNotFoundError: No module named 'common_io'

I dont see common_io in the requirements.txt. What package is this? I cant find it anywhere.

**Comment by zhaoqf123** [comment]
> ModuleNotFoundError: No module named 'common_io'
> 
> I dont see common_io in the requirements.txt. What package is this? I cant find it anywhere.

You can comment it out and it won't affect the code. It is an Alibaba internal package for reading and dumping data.

I will also update the code to remove it.

Thank you for pointing out.

**Comment by DrobConsulting** [comment]
zhaoqf123 Thanks that fixed the issue :)
