### ISSUE TITLE
Accidentally removed function

### ISSUE THREAD

**Issue by cosmina98** [alibaba/graph-gpt#2]
Hey guys, I got an error during training. Looks like you accidentally removed:
def distribute_sampler(sampler, world_size, rank):
    vec = np.array(sorted(sampler))
    idx = [i for i in range(len(sampler)) if i % world_size == rank]
    sampler = vec[idx].tolist()
    random.shuffle(sampler)
    return sampler
on misc_utils.py after the last commit on that file:)

**Comment by zhaoqf123** [comment]
> Hey guys, I got an error during training. Looks like you accidentally removed: def distribute_sampler(sampler, world_size, rank): vec = np.array(sorted(sampler)) idx = [i for i in range(len(sampler)) if i % world_size == rank] sampler = vec[idx].tolist() random.shuffle(sampler) return sampler on misc_utils.py after the last commit on that file:)

Thank you very much for pointing out. We have moved the function to `loader_utils.py`, and the reference was not updated in `train_supervised.py`.

We have fixed the bug in the latest commit. Thank you. :)
