### ISSUE TITLE
About pre-training and fine-tuning arithmetic.

### ISSUE THREAD

**Issue by AI7Xiao** [alibaba/graph-gpt#4]
Thank you very much for the code repository! I learnt a lot about graph modelling from your work.
I'm more concerned about the fact that your article mentions the use of a V100 32G graphics cluster. May I ask for the pre-training and fine-tuning of graphGPT, how many V100 32G did you use respectively?

As I want to try to do replication, I have 8 NVIDIA A100 80G at the moment.

Any reply will be greatly appreciated!

**Comment by zhaoqf123** [comment]
> Thank you very much for the code repository! I learnt a lot about graph modelling from your work. I'm more concerned about the fact that your article mentions the use of a V100 32G graphics cluster. May I ask for the pre-training and fine-tuning of graphGPT, how many V100 32G did you use respectively?
> 
> As I want to try to do replication, I have 8 NVIDIA A100 80G at the moment.
> 
> Any reply will be greatly appreciated!

Thank you for your interest in our work.

Simply speaking, 8 A100 is good enough for model size up to 0.5B, i.e., base48 model (=>hidden_size=768, num_layers=48).

In our practice, we train 2B model for ogbl-ppa using 32 Nvidia L40S in pre-train and fine-tune. We train 2B model for PCQM4M-v2 using 16 L40S in pre-train and fine-tune.

To find the best practice in your settings, we suggest you start from mini/small model size as suggested in https://github.com/alibaba/graph-gpt/issues/3#issuecomment-2469782428

For example, 1 A100 should be good enough for mini/small model.
